### PR TITLE
Fix node-integration and preload

### PR DESCRIPTION
**Pull request by unional**
I didn't change the API. You can change it when you see fit. :grinning:

### CODE REVIEW

**Comment by unional** [comment]
Oops. Let me check

**Comment by unional** [comment]
Fixed a typo.  The `nodeIntegration` warning actually seems to be from `browser-window` itself. :wink:

**Comment by unional** [comment]
btw,
```js
  "devDependencies": {
    "concat-stream": "^1.5.1",
    "electron-prebuilt": "^0.36.12",
    "tape": "^4.2.2"
  },
  "license": "MIT",
  "dependencies": {
    "electron-prebuilt": "^0.37.2",
    "stream-read": "^1.1.2"
  },
```
the devDep of electrion-prebuilt seems to be extra?

**Comment by juliangruber** [comment]
published as 2.6.2. also i de-duped the dev deps.

**Pull request merged**
